language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
matrix:
  allow_failures:
    - python: "2.5"
install:
  - pip install --use-mirrors nose coverage
script:
  - coverage erase
# Unit tests
  - coverage run -a setup.py test
# Integration test
  - coverage run -a virtualenv.py --distribute ./test-venv-01
# Another integration test, where we must download
  - cp -t bin virtualenv.py; coverage run -a bin/virtualenv.py --distribute ./test-venv-02
# Also test with setuptools if we are on Python 2
  - python -c 'import sys; sys.exit(0 if sys.version_info >= (3,) else 1)' || coverage run -a virtualenv.py --setuptools ./test-venv-03
# Setuptools + download
  - python -c 'import sys; sys.exit(0 if sys.version_info >= (3,) else 1)' || coverage run -a bin/virtualenv.py --setuptools ./test-venv-04
# How was our test coverage?
  - coverage report --show-missing
notifications:
  irc:
    channels: "irc.freenode.org#pip"
    on_success: change
    on_failure: change
