language: python

sudo: false

env:
  - INSTALL_FIRST=yes TOXENV=py26
  - INSTALL_FIRST=yes TOXENV=py27
  - INSTALL_FIRST=yes TOXENV=py32
  - INSTALL_FIRST=yes TOXENV=py33
  - INSTALL_FIRST=yes TOXENV=py34
  - INSTALL_FIRST=yes TOXENV=pypy
  - INSTALL_FIRST=yes TOXENV=pypy3 
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=docs
  - TOXENV=pep8
  - TOXENV=py2pep8
  - TOXENV=packaging

install:
  - if [[ $INSTALL_FIRST == yes ]]; then pip install .; fi
  - pip install tox nameless

script: tox
