language: python

matrix:
  include:
    # Based on https://docs.python.org/devguide/#status-of-python-branches
    - python: 2.7
      env: TOXENV=python2.7
    - python: 3.4
      env: TOXENV=python3.4
    - python: 3.5
      env: TOXENV=python3.5
    - python: 3.6
      env: TOXENV=python3.6
    - python: pypy
      env: TOXENV=pypy
    - python: 3.6
      env: TOXENV=crosspython3
    - python: 2.7
      env: TOXENV=crosspython2
    - python: 2.7
      env: TOXENV=docs

install:
  # detecting invalid commits that missed rebuild-script.
  - ./bin/rebuild-script.py && git diff-files --quiet || { >&2 echo "Code submitted without running ./bin/rebuild-script.py first."; exit 1; }
  - pip install tox

script:
 - ./bin/rebuild-script.py
 - tox
 - ./tests/test_activate.sh
 - |-
   function check_status() {
     if ! git diff-index --quiet --ignore-submodules=all HEAD --; then
       echo 'Uncommitted changes detected:';
       git diff-index HEAD --;
       return 1;
     fi;
   }

sudo: false # Use container based builds
cache: pip

branches:
  only:
    - master
    - develop
    - rewrite

notifications:
  irc:
    channels:
      - "irc.freenode.org#pypa-dev"
    use_notice: true
    skip_join: true
